{application,tirexs,
             [{applications,[kernel,stdlib,elixir,exjsx,inets,logger]},
              {description,"An Elixir flavored DSL for building JSON based queries to Elasticsearch engine\n"},
              {modules,['Elixir.Tirexs','Elixir.Tirexs.Bulk',
                        'Elixir.Tirexs.DSL','Elixir.Tirexs.DSL.Behaviour',
                        'Elixir.Tirexs.DSL.Logic','Elixir.Tirexs.ENV',
                        'Elixir.Tirexs.ElasticSearch.Settings',
                        'Elixir.Tirexs.HTTP','Elixir.Tirexs.Index.Logic',
                        'Elixir.Tirexs.Index.Settings','Elixir.Tirexs.Logger',
                        'Elixir.Tirexs.Manage.Aliases',
                        'Elixir.Tirexs.Mapping','Elixir.Tirexs.MultiGet',
                        'Elixir.Tirexs.Percolator','Elixir.Tirexs.Query',
                        'Elixir.Tirexs.Query.Filter',
                        'Elixir.Tirexs.Query.Logic','Elixir.Tirexs.Resources',
                        'Elixir.Tirexs.Resources.APIs',
                        'Elixir.Tirexs.Resources.Document',
                        'Elixir.Tirexs.Resources.Indices',
                        'Elixir.Tirexs.Resources.Search',
                        'Elixir.Tirexs.Search','Elixir.Tirexs.Search.Aggs',
                        'Elixir.Tirexs.Search.Rescore',
                        'Elixir.Tirexs.Search.Suggest',
                        'Elixir.Tirexs.Search.Warmer']},
              {registered,[]},
              {vsn,"0.8.15"},
              {env,[{uri,#{'__struct__' => 'Elixir.URI',
                           authority => <<"127.0.0.1:9200">>,fragment => nil,
                           host => <<"127.0.0.1">>,path => nil,port => 9200,
                           query => nil,scheme => <<"http">>,
                           userinfo => nil}}]}]}.
